#application: orbital-stage-648 #dev.xinyue ->chopping
#application: nasa-photo-app #dev.xinyue
application: nasa-photo-dev #chris.de

version: 1
runtime: go
api_version: go1
instance_class: F4_1G
automatic_scaling:
  max_concurrent_requests: 500

handlers:
- url: /.*
  script: _go_app
